### ISSUE TITLE
AddonsLayer: Conditions should be unique

### ISSUE THREAD

**Issue by saada** [fidelity/kraan#154]
**Is your feature request related to a problem? Please describe.**
I would like to use `kubectl wait addonslayers --for=condition=Deployed --all` to wait for layers to complete. This is not possible today due to duplication of conditions per version. So if v1 has Deployed=false and v2 has Deployed=true, the wait command still fails as it likely chooses the first condition it finds.

**Describe the solution you'd like**
If the intention was to use Conditions as a log, we should instead use the object's Events instead. Conditions are not intended to be logs. They should be unique per condition type.

**Describe alternatives you've considered**
I tried using the AddonsLayers.status.state but that is not accessible via kubectl wait.

**Comment by paulcarlton-ww** [comment]
Will fix this tomorrow
