### ISSUE TITLE
hard code kraan-controller in template but build kraan/kraan-controller-prerelease:v0.1.20-dev

### ISSUE THREAD

**Issue by paulcarlton-ww** [fidelity/kraan#178]
We hard code kraan-controller in https://github.com/fidelity/kraan/blob/711059b0ac74d4cff34d3eadf3fbe8fbb1d94553/chart/templates/kraan/deployment.yaml#L38
but in ci we build  kraan/kraan-controller-prerelease:v0.1.20-dev, seems we should have a value to override this so we can use that build?

Am I missing something?

@saada thoughts

**Comment by saada** [comment]
You're absolutely right. I'll create a PR to fix this.
