### ISSUE TITLE
Add deployment of new chart to ci

### ISSUE THREAD

**Issue by paulcarlton-ww** [fidelity/kraan#181]
As discussed with @saada we should add a step to the ci to generate and deploy a new chart version if the version in https://github.com/fidelity/kraan/blob/master/chart/Chart.yaml#L6 has been updated.

**Comment by saada** [comment]
Does this mean the chart version release cadence will no no longer match `./VERSION`? Meaning docker image version and chart version might be different?

**Comment by paulcarlton-ww** [comment]
Yes chart version is determined by https://github.com/fidelity/kraan/blob/master/chart/Chart.yaml#L6
The image tag is set by VERSION. If you update the VERSION generally you will update the appVersion at https://github.com/fidelity/kraan/blob/master/chart/Chart.yaml#L5 and if you do that you should really update version at https://github.com/fidelity/kraan/blob/master/chart/Chart.yaml#L6 
So if you generate a new image you should create a new chart with that new image tag as the appVersion.
Seems to me if you make a docs/script change that doesn't impact the image build we should not increment the VERSION.
if the change is to the chart you would increment the chart version but appVersion would be the same.
Make any sense?
