### ISSUE TITLE
Set observedGeneration under condition Ready 

### ISSUE THREAD

**Issue by kishoregv** [fidelity/kraan#209]
**Is your feature request related to a problem? Please describe.**
Currently, `observedGeneration` is only set in status level for `al` resource. It would be helpful to set `observedGeneration` under conditions as well. To reliably rely on kubectl wait [command](https://github.com/kubernetes/kubernetes/pull/97408/files) for ready condition to be met.

If the previous condition was ready for HR resource then, sometime kubectl wait will confirm to soon as condition met based on previous Ready condition.

**Describe the solution you'd like**
`observedGeneration` should be set under condition.

**Describe alternatives you've considered**
We have are sleeping for 30 secs hoping the status will be updated in the mean time.

**Comment by wangli1030** [comment]
Has been implemented by PR #226
